set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR m68k)

set(AMIGA_TOOLCHAIN_PATH "/opt/amiga" CACHE PATH "m68k-amigaos toolchain prefix")
set(AMIGA_TARGET "m68k-amigaos" CACHE STRING "AmigaOS target triple")

set(CMAKE_C_COMPILER "${AMIGA_TOOLCHAIN_PATH}/bin/${AMIGA_TARGET}-gcc")
set(CMAKE_CXX_COMPILER "${AMIGA_TOOLCHAIN_PATH}/bin/${AMIGA_TARGET}-g++")
set(CMAKE_ASM_COMPILER "${AMIGA_TOOLCHAIN_PATH}/bin/${AMIGA_TARGET}-gcc")
set(CMAKE_AR "${AMIGA_TOOLCHAIN_PATH}/bin/${AMIGA_TARGET}-ar")
set(CMAKE_RANLIB "${AMIGA_TOOLCHAIN_PATH}/bin/${AMIGA_TARGET}-ranlib")
set(CMAKE_OBJCOPY "${AMIGA_TOOLCHAIN_PATH}/bin/${AMIGA_TARGET}-objcopy")
set(CMAKE_OBJDUMP "${AMIGA_TOOLCHAIN_PATH}/bin/${AMIGA_TARGET}-objdump")
set(CMAKE_STRIP "${AMIGA_TOOLCHAIN_PATH}/bin/${AMIGA_TARGET}-strip")

set(CMAKE_FIND_ROOT_PATH
    "${AMIGA_TOOLCHAIN_PATH}"
    "${AMIGA_TOOLCHAIN_PATH}/${AMIGA_TARGET}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# CMake cannot execute Amiga binaries during configure checks.
set(CMAKE_CROSSCOMPILING_EMULATOR "" CACHE STRING "Amiga emulator" FORCE)
